FROM apache/airflow:2.10.5-python3.10

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    ollama==0.6.3 \
    psycopg2-binary==2.9.13

RUN pip install --no-cache-dir \
    torch==2.14.0+cpu \
    --extra-index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir \
    sentence-transformers==6.1.0

COPY src /opt/airflow/src
COPY airflow/dags /opt/airflow/dags